In [34]:
import pandas as pd
df=pd.read_csv("Customer_orders.csv") 
df

    OrderID    CustomerName     Product  Quantity  PricePerUnit
0       101        John Doe      Laptop       1.0       1200.50
1       102      Jane Smith       Phone       2.0        699.99
2       103             NaN          TV       1.0      45000.00
3       104      Mike Brown      Tablet       1.0      20000.00
4       105   Alice Johnson     Speaker       3.0       1500.00
5       105   Alice Johnson     Speaker       3.0       1500.00
6       106             NaN  Smartwatch      -1.0       2999.00
7       107     David Clark  Headphones       2.0       5000.00
8       108       Eve Black     Monitor       1.0           NaN
9       109     Frank White    Keyboard       1.0        200.00
10      110     Emily Green       Mouse       NaN         50.00
11      111         Tom Lee  Smartwatch       2.0       2500.00
12      112     Nancy Moore   Earphones       1.0        299.99
13      113       John Snow      Laptop       3.0      75000.00
14      114      Emma Stone       Phone       1.0        999.99
15      115    Daniel Craig      Tablet       4.0           NaN
16      116   Sophia Turner     Speaker       2.0       1999.00
17      117   Michael Scott         NaN       1.0       3500.00
18      118     Jim Halpert  Headphones       2.0       1500.00
19      119      Pam Beesly    Keyboard       3.0       1200.00
20      120  Dwight Schrute       Mouse       2.0        399.99

In [36]:
# 1. Handle Missing Values

# a. Replace missing CustomerName with "Unknown"
df["CustomerName"] = df["CustomerName"].fillna("Unknown")
df

    OrderID    CustomerName     Product  Quantity  PricePerUnit
0       101        John Doe      Laptop       1.0       1200.50
1       102      Jane Smith       Phone       2.0        699.99
2       103         Unknown          TV       1.0      45000.00
3       104      Mike Brown      Tablet       1.0      20000.00
4       105   Alice Johnson     Speaker       3.0       1500.00
5       105   Alice Johnson     Speaker       3.0       1500.00
6       106         Unknown  Smartwatch      -1.0       2999.00
7       107     David Clark  Headphones       2.0       5000.00
8       108       Eve Black     Monitor       1.0           NaN
9       109     Frank White    Keyboard       1.0        200.00
10      110     Emily Green       Mouse       NaN         50.00
11      111         Tom Lee  Smartwatch       2.0       2500.00
12      112     Nancy Moore   Earphones       1.0        299.99
13      113       John Snow      Laptop       3.0      75000.00
14      114      Emma Stone       Phone       1.0        999.99
15      115    Daniel Craig      Tablet       4.0           NaN
16      116   Sophia Turner     Speaker       2.0       1999.00
17      117   Michael Scott         NaN       1.0       3500.00
18      118     Jim Halpert  Headphones       2.0       1500.00
19      119      Pam Beesly    Keyboard       3.0       1200.00
20      120  Dwight Schrute       Mouse       2.0        399.99

In [37]:
# b. Replace missing Product with "Unknown Product"
df["Product"] = df["Product"].fillna("Unknown Product")
df

    OrderID    CustomerName          Product  Quantity  PricePerUnit
0       101        John Doe           Laptop       1.0       1200.50
1       102      Jane Smith            Phone       2.0        699.99
2       103         Unknown               TV       1.0      45000.00
3       104      Mike Brown           Tablet       1.0      20000.00
4       105   Alice Johnson          Speaker       3.0       1500.00
5       105   Alice Johnson          Speaker       3.0       1500.00
6       106         Unknown       Smartwatch      -1.0       2999.00
7       107     David Clark       Headphones       2.0       5000.00
8       108       Eve Black          Monitor       1.0           NaN
9       109     Frank White         Keyboard       1.0        200.00
10      110     Emily Green            Mouse       NaN         50.00
11      111         Tom Lee       Smartwatch       2.0       2500.00
12      112     Nancy Moore        Earphones       1.0        299.99
13      113       John Snow           Laptop       3.0      75000.00
14      114      Emma Stone            Phone       1.0        999.99
15      115    Daniel Craig           Tablet       4.0           NaN
16      116   Sophia Turner          Speaker       2.0       1999.00
17      117   Michael Scott  Unknown Product       1.0       3500.00
18      118     Jim Halpert       Headphones       2.0       1500.00
19      119      Pam Beesly         Keyboard       3.0       1200.00
20      120  Dwight Schrute            Mouse       2.0        399.99

In [38]:
# c. Drop rows with missing Quantity
df = df.dropna(subset=["Quantity"])
df

    OrderID    CustomerName          Product  Quantity  PricePerUnit
0       101        John Doe           Laptop       1.0       1200.50
1       102      Jane Smith            Phone       2.0        699.99
2       103         Unknown               TV       1.0      45000.00
3       104      Mike Brown           Tablet       1.0      20000.00
4       105   Alice Johnson          Speaker       3.0       1500.00
5       105   Alice Johnson          Speaker       3.0       1500.00
6       106         Unknown       Smartwatch      -1.0       2999.00
7       107     David Clark       Headphones       2.0       5000.00
8       108       Eve Black          Monitor       1.0           NaN
9       109     Frank White         Keyboard       1.0        200.00
11      111         Tom Lee       Smartwatch       2.0       2500.00
12      112     Nancy Moore        Earphones       1.0        299.99
13      113       John Snow           Laptop       3.0      75000.00
14      114      Emma Stone            Phone       1.0        999.99
15      115    Daniel Craig           Tablet       4.0           NaN
16      116   Sophia Turner          Speaker       2.0       1999.00
17      117   Michael Scott  Unknown Product       1.0       3500.00
18      118     Jim Halpert       Headphones       2.0       1500.00
19      119      Pam Beesly         Keyboard       3.0       1200.00
20      120  Dwight Schrute            Mouse       2.0        399.99

In [45]:
# d. Replace missing PricePerUnit with the mean
mean_price = df["PricePerUnit"].mean()
df["PricePerUnit"] = df["PricePerUnit"].fillna(mean_price)
df

C:\Users\A Praisy Emberline\AppData\Local\Temp\ipykernel_1304\31750993.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["PricePerUnit"] = df["PricePerUnit"].fillna(mean_price)

    OrderID    CustomerName          Product  Quantity  PricePerUnit
0       101        John Doe           Laptop       1.0   1200.500000
1       102      Jane Smith            Phone       2.0    699.990000
2       103         Unknown               TV       1.0  45000.000000
3       104      Mike Brown           Tablet       1.0  20000.000000
4       105   Alice Johnson          Speaker       3.0   1500.000000
5       105   Alice Johnson          Speaker       3.0   1500.000000
6       106         Unknown       Smartwatch      -1.0   2999.000000
7       107     David Clark       Headphones       2.0   5000.000000
8       108       Eve Black          Monitor       1.0   9194.358889
9       109     Frank White         Keyboard       1.0    200.000000
11      111         Tom Lee       Smartwatch       2.0   2500.000000
12      112     Nancy Moore        Earphones       1.0    299.990000
13      113       John Snow           Laptop       3.0  75000.000000
14      114      Emma Stone            Phone       1.0    999.990000
15      115    Daniel Craig           Tablet       4.0   9194.358889
16      116   Sophia Turner          Speaker       2.0   1999.000000
17      117   Michael Scott  Unknown Product       1.0   3500.000000
18      118     Jim Halpert       Headphones       2.0   1500.000000
19      119      Pam Beesly         Keyboard       3.0   1200.000000
20      120  Dwight Schrute            Mouse       2.0    399.990000

In [28]:
# 2. Correct Invalid Values

# Convert negative Quantity values into positive values
df["Quantity"] = df["Quantity"].abs()
df

,OrderID,CustomerName,Product,Quantity,PricePerUnit,TotalPrice
0,101,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,1200.500000,1200.500000
1,102,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,699.990000,1399.980000
2,103,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,45000.000000,45000.000000
3,104,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,20000.000000,20000.000000
4,105,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,1500.000000,4500.000000
6,106,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,2999.000000,2999.000000
7,107,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,5000.000000,10000.000000
8,108,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,9194.358889,9194.358889
9,109,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,200.000000,200.000000
11,111,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,2500.000000,5000.000000
12,112,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,299.990000,299.990000
13,113,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,75000.000000,225000.000000
14,114,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,999.990000,999.990000
15,115,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,4,9194.358889,36777.435556
16,116,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,1999.000000,3998.000000
17,117,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,3500.000000,3500.000000
18,118,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,1500.000000,3000.000000
19,119,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,1200.000000,3600.000000
20,120,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,399.990000,799.980000

In [29]:
# 3. Remove Duplicates

# Identify the number of duplicate rows
duplicate_count = df.duplicated().sum()
df

,OrderID,CustomerName,Product,Quantity,PricePerUnit,TotalPrice
0,101,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,1200.500000,1200.500000
1,102,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,699.990000,1399.980000
2,103,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,45000.000000,45000.000000
3,104,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,20000.000000,20000.000000
4,105,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,1500.000000,4500.000000
6,106,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,2999.000000,2999.000000
7,107,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,5000.000000,10000.000000
8,108,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,9194.358889,9194.358889
9,109,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,200.000000,200.000000
11,111,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,2500.000000,5000.000000
12,112,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,299.990000,299.990000
13,113,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,75000.000000,225000.000000
14,114,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,999.990000,999.990000
15,115,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,4,9194.358889,36777.435556
16,116,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,1999.000000,3998.000000
17,117,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,3500.000000,3500.000000
18,118,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,1500.000000,3000.000000
19,119,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,1200.000000,3600.000000
20,120,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,399.990000,799.980000

In [30]:
# Remove duplicate rows
df = df.drop_duplicates()
df

,OrderID,CustomerName,Product,Quantity,PricePerUnit,TotalPrice
0,101,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,1200.500000,1200.500000
1,102,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,699.990000,1399.980000
2,103,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,45000.000000,45000.000000
3,104,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,20000.000000,20000.000000
4,105,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,1500.000000,4500.000000
6,106,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,2999.000000,2999.000000
7,107,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,5000.000000,10000.000000
8,108,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,9194.358889,9194.358889
9,109,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,200.000000,200.000000
11,111,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,2500.000000,5000.000000
12,112,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,299.990000,299.990000
13,113,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,75000.000000,225000.000000
14,114,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,999.990000,999.990000
15,115,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,4,9194.358889,36777.435556
16,116,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,1999.000000,3998.000000
17,117,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,3500.000000,3500.000000
18,118,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,1500.000000,3000.000000
19,119,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,1200.000000,3600.000000
20,120,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,399.990000,799.980000

In [31]:
# 4. Converting Data Types

# Convert Quantity to integer
df["Quantity"] = df["Quantity"].astype(int)
df

,OrderID,CustomerName,Product,Quantity,PricePerUnit,TotalPrice
0,101,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,1200.500000,1200.500000
1,102,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,699.990000,1399.980000
2,103,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,45000.000000,45000.000000
3,104,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,20000.000000,20000.000000
4,105,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,1500.000000,4500.000000
6,106,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,2999.000000,2999.000000
7,107,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,5000.000000,10000.000000
8,108,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,9194.358889,9194.358889
9,109,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,200.000000,200.000000
11,111,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,2500.000000,5000.000000
12,112,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,299.990000,299.990000
13,113,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,75000.000000,225000.000000
14,114,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,999.990000,999.990000
15,115,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,4,9194.358889,36777.435556
16,116,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,1999.000000,3998.000000
17,117,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,3500.000000,3500.000000
18,118,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,1500.000000,3000.000000
19,119,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,1200.000000,3600.000000
20,120,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,399.990000,799.980000

In [32]:
# 5. Create Derived Column

# Calculate TotalPrice
df["TotalPrice"] = df["Quantity"] * df["PricePerUnit"]
df

,OrderID,CustomerName,Product,Quantity,PricePerUnit,TotalPrice
0,101,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,1200.500000,1200.500000
1,102,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,699.990000,1399.980000
2,103,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,45000.000000,45000.000000
3,104,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,20000.000000,20000.000000
4,105,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,1500.000000,4500.000000
6,106,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,2999.000000,2999.000000
7,107,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,5000.000000,10000.000000
8,108,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,9194.358889,9194.358889
9,109,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,200.000000,200.000000
11,111,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,2500.000000,5000.000000
12,112,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,299.990000,299.990000
13,113,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,75000.000000,225000.000000
14,114,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,999.990000,999.990000
15,115,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,4,9194.358889,36777.435556
16,116,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,1999.000000,3998.000000
17,117,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,1,3500.000000,3500.000000
18,118,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,1500.000000,3000.000000
19,119,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,3,1200.000000,3600.000000
20,120,<bound method NDFrame.fillna of 0 Jo...,<bound method NDFrame.fillna of 0 ...,2,399.990000,799.980000